name: PHP tests

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']

    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Check PHP version
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Lint PHP files
        run: |
          curl -Ls https://github.com/overtrue/phplint/releases/latest/download/phplint.phar -o /usr/local/bin/phplint
          chmod +x /usr/local/bin/phplint
          /usr/local/bin/phplint --no-cache --no-progress -v        

      - name: Coding standards
        run: ./vendor/bin/phpcs

      - name: PHPUnit
        run: ./vendor/bin/phpunit
